test 8
snoack/reviewable-test pull request #11
Opened 2023-09-29 18:30 UTC by snoack

2023-09-29 18:30 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`bitmask-openvpn.py` line 169 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-NfXCFBYAZCITkFD7rq-:-NfXCFBYAZCITkFD7rq0:b9qtc54) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L169)):*
> ```Python
>     return True
> 
> def restart_openvpn(unused):
> ```

some comment


<!-- Sent from Reviewable.io -->

2023-09-29 18:43 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`bitmask-openvpn.py` line 169 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-NfXCFBYAZCITkFD7rq-:-NfXFElXBLpt5Dlc9s4X:bxk3wd9) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L169)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

some comment
</blockquote></details>

another comment


<!-- Sent from Reviewable.io -->

2023-10-02 18:51 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, all discussions resolved

___
*[`bitmask-openvpn.py` line 177 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-NflikSn26X-j3USeP-3:-NflikSn26X-j3USeP-4:bb7p34n) ([raw file](https://github.com/snoack/reviewable-test/blob/ad30c52de5f4eae836cbd90b3f55d80f1eb305f4/bitmask-openvpn.py#L177)):*
> ```Python
>         logging.info("PID file does not exist, OpenVPN doesn't seem to be running")
>     except ProcessLookupError:
>         logging.warning("No such process, cannot restart OpenVPN")
> ```

test


<!-- Sent from Reviewable.io -->

2023-10-02 18:52 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, all discussions resolved

___
*[`bitmask-openvpn.py` line 177 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-NflikSn26X-j3USeP-3:-Nflix-89Js_ZhzEpnLq:b2ni2sh) ([raw file](https://github.com/snoack/reviewable-test/blob/ad30c52de5f4eae836cbd90b3f55d80f1eb305f4/bitmask-openvpn.py#L177)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

test
</blockquote></details>

foo


<!-- Sent from Reviewable.io -->

2023-10-02 19:00 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`bitmask-openvpn.py` line 178 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-NflkV9p6Dn08ql3f5ha:-NflkV9p6Dn08ql3f5hb:b2ni41j) ([raw file](https://github.com/snoack/reviewable-test/blob/ad30c52de5f4eae836cbd90b3f55d80f1eb305f4/bitmask-openvpn.py#L178)):*
> ```Python
>     except ProcessLookupError:
>         logging.warning("No such process, cannot restart OpenVPN")
> ```

hey


<!-- Sent from Reviewable.io -->

2023-10-02 19:01 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`bitmask-openvpn.py` line 178 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-NflkV9p6Dn08ql3f5ha:-Nfll-RH-X_ydDvWSJmR:b2yk4yq) ([raw file](https://github.com/snoack/reviewable-test/blob/ad30c52de5f4eae836cbd90b3f55d80f1eb305f4/bitmask-openvpn.py#L178)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

foo
</blockquote></details>

change dispo


<!-- Sent from Reviewable.io -->

2023-10-03 20:01 UTC, snoack commented on bitmask-openvpn.py
>      parser = argparse.ArgumentParser()
gh test c

2023-10-03 20:03 UTC, snoack commented on README-renamed-in-base.txt
> -renamed in base
foo

2023-10-04 20:35 UTC, snoack reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 1 of 2 files reviewed, 3 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-10-15 17:38 UTC, snoack commented on bitmask-openvpn.py
>      logging.info("Restarting OpenVPN")
Test comment.

2024-10-17 17:28 UTC, test-user-96 commented on bitmask-openvpn.py
hey

2024-10-17 20:29 UTC, snoack commented on bitmask-openvpn.py
>      logging.info("Restarting OpenVPN")
foo

2024-10-30 00:20 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @test-user-96)

___
*[`README-renamed-in-base.txt` line 3 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OAPmxHP9KFHgsJslLmK:-OAPmxHP9KFHgsJslLmL:bb7p34n) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/README-renamed-in-base.txt#L3)):*
> ```help
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum molestie est eget felis aliquam, vitae tempor sem venenatis. Vestibulum nec finibus velit, ut condimentum ligula. Quisque vitae diam luctus, imperdiet enim vel, mattis purus. Quisque ac mi leo. Donec blandit ligula non lorem lobortis mattis. Maecenas enim libero, tempor a imperdiet volutpat, vulputate et purus. Aenean maximus diam neque, dignissim efficitur sem tristique at. Donec at felis dui. Praesent ut quam mauris. Maecenas congue fringilla sem, et pulvinar nunc accumsan nec.
> 
> Etiam nec hendrerit est. Maecenas mattis nunc eu eros aliquam tincidunt. Donec convallis lacinia ipsum vitae posuere. Cras convallis nulla sagittis purus tempus scelerisque. Integer turpis nulla, viverra in faucibus vel, ultricies quis felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus commodo blandit elit, sed consectetur turpis.
> ```

test


<!-- Sent from Reviewable.io -->

2024-10-30 17:18 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @test-user-96)

___
*[`bitmask-openvpn.py` line 170 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#gh-1801646173:-OATQblN9UV9MpBGaJei:b2nhzhq) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L170)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

ddd
</blockquote></details>

bar


<!-- Sent from Reviewable.io -->

2024-11-05 02:00 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-05 02:30 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-05 02:33 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-05 02:33 UTC, snoack commented on bitmask-openvpn.py
>      logging.info("Restarting OpenVPN")
___
*[`bitmask-openvpn.py` line 170 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#gh-1801646173:-OAu1MUM-j7F3wEIA7wY:b-j5phsv) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L170)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

bar
</blockquote></details>

test reply

2024-11-06 01:42 UTC, snoack commented on README-renamed-in-base.txt
> -renamed in base
inline reply

2024-11-06 01:50 UTC, snoack commented on bitmask-openvpn.py
> +        logging.warning('No such process, cannot restart OpenVPN')
new inline comment

2024-11-06 01:50 UTC, snoack commented on bitmask-openvpn.py
> +        logging.warning('No such process, cannot restart OpenVPN')
reply

2024-11-06 02:24 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-06 02:24 UTC, snoack commented on bitmask-openvpn.py
> +        logging.warning('No such process, cannot restart OpenVPN')
reply from reviewable

2024-11-06 02:26 UTC, snoack reviewed
<!-- Sent from Reviewable.io -->

2024-11-06 02:26 UTC, snoack commented on bitmask-openvpn.py
> +        logging.warning('No such process, cannot restart OpenVPN')
reply from reviewable adhoc

2024-11-06 20:17 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-06 20:17 UTC, snoack commented on bitmask-openvpn.py
second inline reply

2024-11-06 20:17 UTC, snoack commented on bitmask-openvpn.py
>      logging.info("Restarting OpenVPN")
another inline reply

2024-11-06 20:18 UTC, snoack reviewed
<!-- Sent from Reviewable.io -->

2024-11-06 20:18 UTC, snoack commented on bitmask-openvpn.py
> +        logging.warning('No such process, cannot restart OpenVPN')
another

2024-11-07 02:08 UTC, snoack commented on README-renamed-in-base.txt
>  In a efficitur dolor. Suspendisse bibendum dui urna, ac consectetur enim imperdiet sit amet. In pharetra eu justo a venenatis. Nullam hendrerit imperdiet augue, a vehicula nibh bibendum a. Nam at est
testestest

2024-11-07 20:48 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @test-user-96)

___
*[`bitmask-openvpn.py` line 166 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7Nbho2pIo8JJJI691:-OB7Nbho2pIo8JJJI692:bvsquyz) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L166)):*
> ```Python
> 
>     logging.info("Writing new certificate to %s", CERT_FILENAME)
>     with open(CERT_FILENAME, "wb") as file: file.write(pem)
> ```

comment 1
___
*[`bitmask-openvpn.py` line 175 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7Ndwf1-kSkPHT_Hke:-OB7Ndwf1-kSkPHT_Hkf:bvsquz0) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L175)):*
> ```Python
>             os.kill(int(file.read()), signal.SIGHUP)
>     except FileNotFoundError:
>         logging.info("PID file does not exist, OpenVPN doesn't seem to be running")
> ```

comment 2
___
*[`bitmask-openvpn.py` line 187 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7Nf6DAsa-4afUZwOv:-OB7Nf6DAsa-4afUZwOw:bvsquz1) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L187)):*
> ```Python
>     check_ca()
>     if update_openvpn_config(args.force) | update_cert(args.force):
>         restart_openvpn()
> ```

comment 3


<!-- Sent from Reviewable.io -->

2024-11-07 20:50 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 13 unresolved discussions (waiting on @test-user-96)

*[a discussion](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7NyRq0M0zHuM-hI3N:-OB7NyRr-BnUP7G4S6oh:bjfk7x4) (no related file):*
new top discussion

___
___
*[`bitmask-openvpn.py` line 0 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7O2Kd4OZMnk51n9B1:-OB7O2Kd4OZMnk51n9B2:b-nw3q7x) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L0)):*
new file level discussion
___
*[`bitmask-openvpn.py` line 165 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7O56R2MMdkIStHh57:-OB7O56R2MMdkIStHh58:bu810oa) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L165)):*
> ```Python
>         return False
> 
>     logging.info("Writing new certificate to %s", CERT_FILENAME)
> ```

new inline discussion


<!-- Sent from Reviewable.io -->

2024-11-07 22:22 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 13 unresolved discussions (waiting on @test-user-96)

*[a discussion](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7NyRq0M0zHuM-hI3N:-OB7i5XM99TT9CJtFeSD:b2ni2sh) (no related file):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

new top discussion
</blockquote></details>

foo

___
___
*[`bitmask-openvpn.py` line  at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7O2Kd4OZMnk51n9B1:-OB7i7cf7GXktyhKJfV6:b2nhzhq) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

new file level discussion
</blockquote></details>

bar


<!-- Sent from Reviewable.io -->

2024-11-07 22:33 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 16 unresolved discussions (waiting on @test-user-96)

*[a discussion](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7kZWJ9oMmSsHXBQIb:-OB7kZWJ9oMmSsHXBQIc:b-503h74) (no related file):*
new top

___
___
*[`bitmask-openvpn.py` line 0 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7kcyc9tC9l9L3CQF4:-OB7kcyd1zaN3Am7H-ln:bmb0oqn) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L0)):*
new file 
___
*[`bitmask-openvpn.py` line 164 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7keOP64a2YWsE_YHg:-OB7keOP64a2YWsE_YHh:b-hbn9r6) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L164)):*
> ```Python
>         logging.error("HTTP request downloading the certificate failed")
>         return False
> ```

new inline


<!-- Sent from Reviewable.io -->

2024-11-07 22:38 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 19 unresolved discussions (waiting on @test-user-96)

*[a discussion](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7kwrA0o7KPh6BlYuL:-OB7kwrA0o7KPh6BlYuM:b3kr0) (no related file):*
1

___
___
*[`bitmask-openvpn.py` line 0 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7lr_K5vaKv4BS1PuY:-OB7lr_K5vaKv4BS1PuZ:b3kr1) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L0)):*
2
___
*[`bitmask-openvpn.py` line 185 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7lvLZ0Wt0GyE1R6iB:-OB7lvLZ0Wt0GyE1R6iC:b3kr2) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L185)):*
> ```Python
>     args = parser.parse_args()
>     logging.getLogger().setLevel(args.log_level)
>     check_ca()
> ```

3


<!-- Sent from Reviewable.io -->

2024-11-07 22:50 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 19 unresolved discussions (waiting on @test-user-96)

*[a discussion](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7kwrA0o7KPh6BlYuL:-OB7oU6ECgsMY1rY07WA:b2nid68) (no related file):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

1
</blockquote></details>

top

___
___
*[`bitmask-openvpn.py` line  at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7O2Kd4OZMnk51n9B1:-OB7oWKh3c231h_L5Kqi:b2ni2sh) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

bar
</blockquote></details>

foo


<!-- Sent from Reviewable.io -->

2024-11-07 22:52 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 19 unresolved discussions (waiting on @test-user-96)

*[a discussion](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7kwrA0o7KPh6BlYuL:-OB7ozTF4zL1PwdlxJAG:b3ksf) (no related file):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

top
</blockquote></details>

d

___
___
*[`bitmask-openvpn.py` line  at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7O2Kd4OZMnk51n9B1:-OB7p-0o4c9fgUMyZNyZ:b3ksu) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

foo
</blockquote></details>

s


<!-- Sent from Reviewable.io -->

2024-11-07 23:00 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 19 unresolved discussions (waiting on @test-user-96)

foo
___
bar
*[a discussion (2)](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7kwrA0o7KPh6BlYuL:-OB7qlQU9f84j5_Xf1m5:b3kr3) (no related file):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

d
</blockquote></details>

4


<!-- Sent from Reviewable.io -->

2024-11-07 23:04 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 21 unresolved discussions (waiting on @test-user-96)

foo
___
bar
*[a discussion (2)](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7reFiAVT1GVrv7w3e:-OB7reFiAVT1GVrv7w3f:b2ni2sh) (no related file):*
foo
___
*[`bitmask-openvpn.py` line 0 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7rfyhAFJ5RMJwKfro:-OB7rfyhAFJ5RMJwKfrp:b2nhzhq) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L0)):*
bar


<!-- Sent from Reviewable.io -->

2024-11-07 23:12 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)

___
*[a discussion](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7tfjC1sqAQIVcopTS:-OB7tfjC1sqAQIVcopTT:b-503h74) (no related file):*
new top
___
*[`bitmask-openvpn.py` line 0 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7the_-m4KBiOxbgNf:-OB7the_-m4KBiOxbgNg:b-d10rgf) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L0)):*
new file


<!-- Sent from Reviewable.io -->

2024-11-12 21:17 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)

___
*[a discussion](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7kwrA0o7KPh6BlYuL:-OBXEFHfB1uSxNzDODZD:b-7k28e3) (no related file):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

4
</blockquote></details>

reply
___
*[`bitmask-openvpn.py` line  at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7O2Kd4OZMnk51n9B1:-OBXEHDf9M_VmaWpVWrS:bb7o15c) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

s
</blockquote></details>

rply


<!-- Sent from Reviewable.io -->

2024-11-12 21:19 UTC, snoack reviewed
test

> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11#-:-OBXEWwMDupfloRYt12N:bb7p34n)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-12 21:19 UTC, snoack commented on bitmask-openvpn.py
rep,ly
<!-- Reviewable comment -OBXEdno-CUAUM6WQeWZ:b-l6mdvj -->
<!-- Sent from Reviewable.io -->

2024-11-13 01:59 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-13 01:59 UTC, snoack commented on README-renamed-in-base.txt
>  In a efficitur dolor. Suspendisse bibendum dui urna, ac consectetur enim imperdiet sit amet. In pharetra eu justo a venenatis. Nullam hendrerit imperdiet augue, a vehicula nibh bibendum a. Nam at est
test
<!-- Reviewable comment -OBYEhun3r1oVg5dzoqX:bb7p34n -->
<!-- Sent from Reviewable.io -->

2024-11-13 01:59 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-13 01:59 UTC, snoack commented on README-renamed-in-base.txt
> -renamed in base
2
<!-- Reviewable comment -OBYEsCh07kdNqodtyJB:b3kr1 -->
<!-- Sent from Reviewable.io -->

2024-11-13 17:19 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)

___
*[a discussion](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7NyRq0M0zHuM-hI3N:-OBaXL3B0GcO2_r7NYOh:bt34od8) (no related file):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

foo
</blockquote></details>

reply 34


<!-- Sent from Reviewable.io -->

2024-11-15 20:48 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)

___
*[`bitmask-openvpn.py` line 166 at r1](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7Nbho2pIo8JJJI691:-OBlZq0RClzO7zadBsEE:b2ni2sh) ([raw file](https://github.com/snoack/reviewable-test/blob/92cf055cd9370f3ccdeb4fa025335c2fdc8912e9/bitmask-openvpn.py#L166)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

comment 1
</blockquote></details>

foo


<!-- Sent from Reviewable.io -->

2024-11-18 21:30 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)

___
*[a discussion](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7reFiAVT1GVrv7w3e:-OC0AeFIALbC_wgCq987:b3ksh) (no related file):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

foo
</blockquote></details>

f


<!-- Sent from Reviewable.io -->

2024-11-18 21:30 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)

___
*[a discussion](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7NyRq0M0zHuM-hI3N:-OC0Ai9M0YCGeiOOCL3V:b3ksf) (no related file):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

reply 34
</blockquote></details>

d


<!-- Sent from Reviewable.io -->

2024-11-18 21:40 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)

___
*[a discussion](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7NyRq0M0zHuM-hI3N:-OC0CyPz6vS8aKEOVwMB:b3ksf) (no related file):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

d
</blockquote></details>

d


<!-- Sent from Reviewable.io -->

2024-11-18 21:46 UTC, snoack reviewed
d

> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11#-:-OC0EJ-y2djMRmV-QLaz:b3ksf)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-18 21:46 UTC, snoack reviewed
d

> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11#-:-OC0EQ2LEms5lXyB2Z1S:b32wh7)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-18 21:49 UTC, snoack reviewed
d

> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11#-:-OC0F3cb4fTrIyq-aFVw:b3ksf)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-18 22:42 UTC, snoack reviewed
s

> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11#-:-OC0R5CHDzRRv_TIOP-Y:b3ksu)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-18 22:42 UTC, snoack reviewed
s

> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11#-:-OC0RAly-q2qni7O2vPW:b3ksu)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-18 22:56 UTC, snoack reviewed
d

> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11#-:-OC0UYcuAREjpwFpQTKI:b3ksf)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-18 22:57 UTC, snoack reviewed
d

> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11#-:-OC0Uag0AaQi_3RWf7Im:b3ksf)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-22 01:14 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)

___
*[a discussion](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7kZWJ9oMmSsHXBQIb:-OCGQusl6wGL0Kjrr_tk:b3ksg) (no related file):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

f
</blockquote></details>

e


<!-- Sent from Reviewable.io -->

2024-11-22 01:17 UTC, snoack reviewed
3

> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11#-:-OCGRDZA5NWWEk9FnTz9:b3kr2)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-22 03:21 UTC, snoack reviewed
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)

___
*[a discussion](http://localhost:8080/reviews/snoack/reviewable-test/11#-OB7kZWJ9oMmSsHXBQIb:-OCGsokO7h9tU4nlIVCG:b2ni1sw) (no related file):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

e
</blockquote></details>

eee


<!-- Sent from Reviewable.io -->

2024-11-22 03:26 UTC, test-user-96 approved these changes
g

> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11#-:-OCGtoHz15-xiAfpzrb_:b3ksi)* status: 0 of 2 files reviewed, 23 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-11-22 03:28 UTC, test-user-96 requested changes
e

2024-11-22 03:28 UTC, closed without merging

2024-11-22 03:29 UTC, snoack reviewed
d

> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/11#-:-OCGt76V4ucwvTwxaA-h:b3ksf)* status: 0 of 2 files reviewed, 23 unresolved discussions (waiting on @test-user-96)



<!-- Sent from Reviewable.io -->

2024-11-22 17:13 UTC, snoack reviewed
foo